<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ADAssessment.Infrastructure\ADAssessment.Infrastructure.csproj" />
    <ProjectReference Include="..\ADAssessment.Plugins\ADAssessment.Plugins.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
